Algoritmo "003"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Gustavo Guanabara
// Descrição   : Exercício 003
// Autor(a)    : Vitor Cunha
// Data atual  : 30/05/2023
Var

   nome : caractere
   salario : real

Inicio

   escreva("Nome do funcionário: ")
   leia(nome)
   escreva("Salário: ")
   leia(salario)
   
   escreval("O funcionário ", nome, " tem um salário de R$", salario:4:2, " em Junho.")

Fimalgoritmo

