Algoritmo "004"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Gustavo Guanabara
// Descrição   : Exercício 004
// Autor(a)    : Vitor Cunha
// Data atual  : 30/05/2023
Var

   valorUm, valorOutro, soma : real

Inicio

   escreva("Digite um valor: ")
   leia(valorUm)
   escreva("Digite outro valor: ")
   leia(valorOutro)
   
   soma <- valorUm + valorOutro

   escreval("A soma de", valorUm, " e", valorOutro, " é igual a", soma, ".")


Fimalgoritmo