Algoritmo "005"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Gustavo Guanabara
// Descrição   : Exercício 005
// Autor(a)    : Vitor Cunha
// Data atual  : 30/05/2023
Var

   notaUm, notaDois, media : real

Inicio

   escreva("Primeira nota: ")
   leia(notaUm)
   escreva("Segunda nota: ")
   leia(notaDois)

   media <- (notaUm + notaDois)/2

   escreva("A média entre", notaUm, " e", notaDois, " é igual a", media)


Fimalgoritmo