Algoritmo "007"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Gustavo Guanabara
// Descrição   : Exercício 007
// Autor(a)    : Vitor Cunha
// Data atual  : 30/05/2023
Var

   numero, dobro, tercaParte : real

Inicio

   escreva("Digite um número: ")
   leia(numero)

   dobro <- numero * 2
   tercaParte <- numero / 3

   escreval("O dobro de", numero," é", dobro)
   escreval("A terça parte de", numero, " é ", tercaParte:4:5)

Fimalgoritmo