Algoritmo "011"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Gustavo Guanabara
// Descrição   : Exercício 011
// Autor(a)    : Vitor Cunha
// Data atual  : 30/05/2023
Var

   a, b, c, delta : real

Inicio

   escreva("Digite o valor de A: ")
   leia(a)
   escreva("Digite o valor de B: ")
   leia(b)
   escreva("Digite o valor de C: ")
   leia(c)

   delta <- (b^2) - (4*a*c)

   escreval("O valor de delta é: ", delta)

Fimalgoritmo