Algoritmo "012"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Gustavo Guanabara
// Descrição   : Exercício 012
// Autor(a)    : Vitor Cunha
// Data atual  : 30/05/2023
Var

   preco, preco_promocional : real

Inicio

   escreva("Digite o preço do produto: R$")
   leia (preco)

   preco_promocional <- preco * 0.95

   escreva("PREÇO PROMOCIONAL: R$", preco_promocional:4:2)

Fimalgoritmo