Algoritmo "048"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Gustavo Guanabara
// Descrição   : Exercício 048
// Autor(a)    : Vitor Cunha
// Data atual  : 30/05/2023
Var

   soma, i, n: inteiro

Inicio

   enquanto i < 7 faca
      escreva("Digite um número: ")
      leia(n)
      soma <- soma + n
      i <- i + 1
   fimenquanto

   escreva("O somatório dos valores é: ", soma)

Fimalgoritmo