Algoritmo "056"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Gustavo Guanabara
// Descrição   : Exercício 056
// Autor(a)    : Vitor Cunha
// Data atual  : 30/05/2023
Var

   soma, n : inteiro

Inicio

   enquanto n <> 1111 faca
      escreva("Digite um número: ")
      leia(n)
      soma <- soma + n
   fimenquanto
   soma <- soma - 1111
   escreva("Somatório: ", soma)


Fimalgoritmo