Algoritmo "087"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Gustavo Guanabara
// Descrição   : Exercício 087
// Autor(a)    : Vitor Cunha
// Data atual  : 30/05/2023
Var

procedimento gerador(x : caractere)
inicio
   escreval("+-------=======------+")
   escreval(x)
   escreval("+-------=======------+")
fimprocedimento


Inicio

gerador("Aprendendo Portugol")

Fimalgoritmo