Algoritmo "088"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Gustavo Guanabara
// Descrição   : Exercício 088
// Autor(a)    : Vitor Cunha
// Data atual  : 30/05/2023
Var

procedimento gerador(x : caractere ; y : inteiro)
Var
   i : inteiro
inicio
   escreval("+-------=======------+")
   para i de 1 ate y faca
      escreval(x)
   fimpara
   escreval("+-------=======------+")
fimprocedimento


Inicio

   gerador("Aprendendo Portugol", 4)

Fimalgoritmo